import { QueryInterface } from 'sequelize';

export default {
  up: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkInsert(
      'ingredients_measures_meals',
      [
        { id_meal: 1, id_ingredient: 433, str_measure: '1 cup'},
        { id_meal: 1, id_ingredient: 364, str_measure: '1 large' },
        { id_meal: 1, id_ingredient: 49, str_measure: '1 large' },
        { id_meal: 1, id_ingredient: 316, str_measure: '1 tbs' },
        { id_meal: 1, id_ingredient: 104, str_measure: '2 tsp' },
        { id_meal: 1, id_ingredient: 232, str_measure: '1 tsp' },
        { id_meal: 1, id_ingredient: 214, str_measure: '1/2 tsp' },
        { id_meal: 1, id_ingredient: 313, str_measure: '1/2 tsp' },
        { id_meal: 1, id_ingredient: 29, str_measure: '1/4 tsp' },
        { id_meal: 1, id_ingredient: 265, str_measure: '1/4 tsp' },
        { id_meal: 1, id_ingredient: 328, str_measure: '4 cups' },
        { id_meal: 1, id_ingredient: 333, str_measure: '1 cup' },
        { id_meal: 1, id_ingredient: 284, str_measure: 'Pinch' },
        { id_meal: 2, id_ingredient: 557, str_measure: '1 Packet' },
        { id_meal: 2, id_ingredient: 387, str_measure: '150g' },
        { id_meal: 2, id_ingredient: 364, str_measure: '150g' },
        { id_meal: 2, id_ingredient: 223, str_measure: '40g' },
        { id_meal: 2, id_ingredient: 281, str_measure: 'Dash' },
        { id_meal: 2, id_ingredient: 244, str_measure: 'Dash' },
        { id_meal: 3, id_ingredient: 601, str_measure: '300ml ' },
        { id_meal: 3, id_ingredient: 529, str_measure: '100ml' },
        { id_meal: 3, id_ingredient: 52, str_measure: '2 tbs' },
        { id_meal: 3, id_ingredient: 576, str_measure: '3 tbs' },
        { id_meal: 3, id_ingredient: 296, str_measure: '1 tbs' },
        { id_meal: 3, id_ingredient: 103, str_measure: '1' },
        { id_meal: 4, id_ingredient: 253, str_measure: '2 large' },
        { id_meal: 4, id_ingredient: 41, str_measure: '2 tbs' },
        { id_meal: 4, id_ingredient: 60, str_measure: '150g' },
        { id_meal: 4, id_ingredient: 364, str_measure: '1 large' },
        { id_meal: 4, id_ingredient: 264, str_measure: '1 large' },
        { id_meal: 4, id_ingredient: 258, str_measure: 'Pinch' },
        { id_meal: 5, id_ingredient: 3, str_measure: '1 lb' },
        { id_meal: 5, id_ingredient: 296, str_measure: '5 tablespoons' },
        { id_meal: 5, id_ingredient: 197, str_measure: '1' },
        { id_meal: 5, id_ingredient: 149, str_measure: '3 cloves' },
        { id_meal: 5, id_ingredient: 364, str_measure: '3 parts ' },
        { id_meal: 5, id_ingredient: 224, str_measure: '4 tbs' },
        { id_meal: 5, id_ingredient: 333, str_measure: '1 lb' },
        { id_meal: 5, id_ingredient: 281, str_measure: '1 pinch' },        
        { id_meal: 6, id_ingredient: 517, str_measure: '3 cups' },
        { id_meal: 6, id_ingredient: 301, str_measure: '6' },
        { id_meal: 6, id_ingredient: 150, str_measure: '4' },
        { id_meal: 6, id_ingredient: 237, str_measure: '1/4 cup' },
        { id_meal: 6, id_ingredient: 104, str_measure: '2 tsp' },
        { id_meal: 6, id_ingredient: 15, str_measure: '1 tsp' },
        { id_meal: 6, id_ingredient: 53, str_measure: '1/2 tsp' },
        { id_meal: 6, id_ingredient: 137, str_measure: 'Spinkling' },
        { id_meal: 6, id_ingredient: 327, str_measure: 'As required' },
        { id_meal: 7, id_ingredient: 253, str_measure: '5 Large' },
        { id_meal: 7, id_ingredient: 224, str_measure: '2 tbs' },
        { id_meal: 7, id_ingredient: 425, str_measure: '1' },
        { id_meal: 7, id_ingredient: 227, str_measure: '5' },
        { id_meal: 7, id_ingredient: 556, str_measure: '1 tbs' },
        { id_meal: 7, id_ingredient: 418, str_measure: '500g' },
        { id_meal: 7, id_ingredient: 123, str_measure: '24 Skinned' },
        { id_meal: 7, id_ingredient: 281, str_measure: 'Pinch' },
        { id_meal: 7, id_ingredient: 244, str_measure: 'Pinch' },
        { id_meal: 8, id_ingredient: 224, str_measure: '1 tblsp' },
        { id_meal: 8, id_ingredient: 14, str_measure: '2' },
        { id_meal: 8, id_ingredient: 364, str_measure: '1 finely chopped ' },
        { id_meal: 8, id_ingredient: 55, str_measure: '1 Stick' },
        { id_meal: 8, id_ingredient: 49, str_measure: '1 medium' },
        { id_meal: 8, id_ingredient: 149, str_measure: '2 cloves chopped' },
        { id_meal: 8, id_ingredient: 387, str_measure: '500g' },
        { id_meal: 8, id_ingredient: 316, str_measure: '1 tbls' },
        { id_meal: 8, id_ingredient: 80, str_measure: '800g' },
        { id_meal: 8, id_ingredient: 177, str_measure: '1 tblsp' },
        { id_meal: 8, id_ingredient: 194, str_measure: '500g' },
        { id_meal: 8, id_ingredient: 101, str_measure: '400ml' },
        { id_meal: 8, id_ingredient: 216, str_measure: '125g' },
        { id_meal: 8, id_ingredient: 235, str_measure: '50g' },
        { id_meal: 8, id_ingredient: 18, str_measure: 'Topping' },
        { id_meal: 9, id_ingredient: 318, str_measure: '1 cup' },
        { id_meal: 9, id_ingredient: 333, str_measure: '2-1/2 cups' },
        { id_meal: 9, id_ingredient: 281, str_measure: '1 tsp' },
        { id_meal: 9, id_ingredient: 320, str_measure: '1/4 tsp' },
        { id_meal: 9, id_ingredient: 153, str_measure: '3 tbs' },
        { id_meal: 9, id_ingredient: 80, str_measure: '1 cup' },
        { id_meal: 9, id_ingredient: 105, str_measure: '1/2 tsp' },
        { id_meal: 9, id_ingredient: 221, str_measure: '1/2 tsp' },
        { id_meal: 9, id_ingredient: 20, str_measure: '2' },
        { id_meal: 9, id_ingredient: 165, str_measure: '1 tbs chopped' },
        { id_meal: 9, id_ingredient: 154, str_measure: '2 tsp shredded' },
        { id_meal: 9, id_ingredient: 83, str_measure: '2 tsp' },
        { id_meal: 9, id_ingredient: 264, str_measure: '1/2 tsp' },
        { id_meal: 9, id_ingredient: 305, str_measure: '1 tsp' },
        { id_meal: 9, id_ingredient: 148, str_measure: '1/4 tsp' },
        { id_meal: 11, id_ingredient: 327, str_measure: 'Dash' },
        { id_meal: 11, id_ingredient: 25, str_measure: '1 Can' },
        { id_meal: 11, id_ingredient: 253, str_measure: '5 thin cut' },
        { id_meal: 11, id_ingredient: 61, str_measure: '2 cups' },
        { id_meal: 12, id_ingredient: 137, str_measure: '2 cups' },
        { id_meal: 12, id_ingredient: 305, str_measure: '1/3 cup' },
        { id_meal: 12, id_ingredient: 15, str_measure: '3 tsp' },
        { id_meal: 12, id_ingredient: 281, str_measure: '½ tsp' },
        { id_meal: 12, id_ingredient: 483, str_measure: '1 beaten' },
        { id_meal: 12, id_ingredient: 211, str_measure: '¾ cup' },
        { id_meal: 12, id_ingredient: 223, str_measure: '3 tbs' },        
        { id_meal: 12, id_ingredient: 347, str_measure: 'garnish' },
        { id_meal: 13, id_ingredient: 38, str_measure: '1 1/2 cups ' },
        { id_meal: 13, id_ingredient: 268, str_measure: '1 1/2 cups ' },
        { id_meal: 13, id_ingredient: 95, str_measure: '1/2 tsp' },
        { id_meal: 13, id_ingredient: 204, str_measure: '2 cups' },
        { id_meal: 13, id_ingredient: 71, str_measure: 'Can' },
        { id_meal: 13, id_ingredient: 364, str_measure: '1 large' },
        { id_meal: 13, id_ingredient: 281, str_measure: 'Sprinking' },
        { id_meal: 13, id_ingredient: 327, str_measure: '1/2 cup ' },
        { id_meal: 14, id_ingredient: 387, str_measure: '400g' },
        { id_meal: 14, id_ingredient: 224, str_measure: '2 tbs' },
        { id_meal: 14, id_ingredient: 583, str_measure: '2' },
        { id_meal: 14, id_ingredient: 364, str_measure: 'Chopped' },
        { id_meal: 14, id_ingredient: 586, str_measure: '1/4 ' },
        { id_meal: 14, id_ingredient: 60, str_measure: '2 sliced' },
        { id_meal: 14, id_ingredient: 582, str_measure: '2 large' },
        { id_meal: 14, id_ingredient: 576, str_measure: '1 cup' },
        { id_meal: 14, id_ingredient: 541, str_measure: '2 tsp' },
        { id_meal: 14, id_ingredient: 244, str_measure: 'Pinch' },
        { id_meal: 14, id_ingredient: 219, str_measure: '2 tsp' },
        { id_meal: 14, id_ingredient: 226, str_measure: '1 1/2 tsp ' },
        { id_meal: 14, id_ingredient: 151, str_measure: '1 1/2 tsp ' },
        { id_meal: 14, id_ingredient: 232, str_measure: '1/2 tsp' },
        { id_meal: 15, id_ingredient: 70, str_measure: '1 kg' },
        { id_meal: 15, id_ingredient: 95, str_measure: '1 tbs' },
        { id_meal: 15, id_ingredient: 104, str_measure: '1 tbs' },
        { id_meal: 15, id_ingredient: 47, str_measure: '1 tbs' },
        { id_meal: 15, id_ingredient: 53, str_measure: '1 tsp' },
        { id_meal: 15, id_ingredient: 232, str_measure: '2 tsp' },
        { id_meal: 15, id_ingredient: 198, str_measure: '2 tbs' },
        { id_meal: 15, id_ingredient: 224, str_measure: '3 tbs' },
        { id_meal: 15, id_ingredient: 162, str_measure: '1 cup' },
        { id_meal: 15, id_ingredient: 150, str_measure: '1' },
        { id_meal: 15, id_ingredient: 201, str_measure: 'Sliced' },
        { id_meal: 15, id_ingredient: 365, str_measure: 'Sliced' },
        { id_meal: 15, id_ingredient: 579, str_measure: '6' },
        { id_meal: 16, id_ingredient: 253, str_measure: '1.5kg' },
        { id_meal: 16, id_ingredient: 20, str_measure: '2 leaves' },
        { id_meal: 16, id_ingredient: 289, str_measure: '2' },
        { id_meal: 16, id_ingredient: 41, str_measure: '3 tbs' },
        { id_meal: 16, id_ingredient: 187, str_measure: '750g' },
        { id_meal: 16, id_ingredient: 283, str_measure: '2' },
        { id_meal: 16, id_ingredient: 211, str_measure: '500ml' },
        { id_meal: 16, id_ingredient: 222, str_measure: 'Grated' },
        { id_meal: 16, id_ingredient: 281, str_measure: 'Pinch' },
        { id_meal: 16, id_ingredient: 244, str_measure: 'Pinch' },
        { id_meal: 17, id_ingredient: 146, str_measure: '250 Grams' },
        { id_meal: 17, id_ingredient: 114, str_measure: '500 Grams' },
        { id_meal: 17, id_ingredient: 152, str_measure: 'Topping' },
        { id_meal: 17, id_ingredient: 180, str_measure: 'Topping' },
        { id_meal: 17, id_ingredient: 201, str_measure: '1 Bulb' },
        { id_meal: 17, id_ingredient: 365, str_measure: '1' },
        { id_meal: 17, id_ingredient: 103, str_measure: '3rd' },
        { id_meal: 17, id_ingredient: 159, str_measure: '100 Grams' },
        { id_meal: 18, id_ingredient: 455, str_measure: '300g' },
        { id_meal: 18, id_ingredient: 21, str_measure: '2' },
        { id_meal: 18, id_ingredient: 211, str_measure: '300ml ' },
        { id_meal: 18, id_ingredient: 123, str_measure: '4' },
        { id_meal: 18, id_ingredient: 237, str_measure: 'Handful' },
        { id_meal: 18, id_ingredient: 95, str_measure: 'Handful' },
        { id_meal: 18, id_ingredient: 327, str_measure: '2 tbs' },
        { id_meal: 18, id_ingredient: 106, str_measure: '2 tsp' },
        { id_meal: 18, id_ingredient: 268, str_measure: '300g' },
        { id_meal: 19, id_ingredient: 139, str_measure: '900g' },
        { id_meal: 19, id_ingredient: 224, str_measure: '2 tbsp' },
        { id_meal: 19, id_ingredient: 287, str_measure: '600ml' },
        { id_meal: 19, id_ingredient: 336, str_measure: '800g' },
        { id_meal: 19, id_ingredient: 248, str_measure: '1 tbsp' },
        { id_meal: 19, id_ingredient: 222, str_measure: 'Grating' },
        { id_meal: 19, id_ingredient: 115, str_measure: '3 tbsp' },
        { id_meal: 19, id_ingredient: 186, str_measure: '200g' },
        { id_meal: 19, id_ingredient: 196, str_measure: '1 finely sliced' },
        { id_meal: 19, id_ingredient: 254, str_measure: '200g peeled raw' },
        { id_meal: 19, id_ingredient: 237, str_measure: 'Large handful' },
        { id_meal: 19, id_ingredient: 113, str_measure: 'Handful' },
        { id_meal: 19, id_ingredient: 197, str_measure: 'Grated zest of 1' },
        { id_meal: 19, id_ingredient: 172, str_measure: '25g grated' },
        { id_meal: 20, id_ingredient: 41, str_measure: '75g' },
        { id_meal: 20, id_ingredient: 196, str_measure: '1kg' },
        { id_meal: 20, id_ingredient: 281, str_measure: '½ tsp' },
        { id_meal: 20, id_ingredient: 101, str_measure: '300ml ' },
        { id_meal: 20, id_ingredient: 483, str_measure: '1' },
        { id_meal: 20, id_ingredient: 122, str_measure: '3' },
        { id_meal: 20, id_ingredient: 222, str_measure: '¼ teaspoon' },
        { id_meal: 20, id_ingredient: 248, str_measure: '225g' },
        { id_meal: 20, id_ingredient: 451, str_measure: '60g' },
        { id_meal: 20, id_ingredient: 59, str_measure: '50g' },
        { id_meal: 20, id_ingredient: 333, str_measure: '2 tbs' },
        { id_meal: 21, id_ingredient: 137, str_measure: '100g ' },
        { id_meal: 21, id_ingredient: 123, str_measure: '2 large' },
        { id_meal: 21, id_ingredient: 211, str_measure: '300ml ' },
        { id_meal: 21, id_ingredient: 307, str_measure: '1 tbls' },
        { id_meal: 21, id_ingredient: 305, str_measure: 'to serve' },
        { id_meal: 21, id_ingredient: 408, str_measure: 'to serve' },
        { id_meal: 21, id_ingredient: 409, str_measure: 'to serve' },
        { id_meal: 22, id_ingredient: 3, str_measure: '500g' },
        { id_meal: 22, id_ingredient: 11, str_measure: '1 large' },
        { id_meal: 22, id_ingredient: 162, str_measure: '150g' },
        { id_meal: 22, id_ingredient: 483, str_measure: '1 beaten' },
        { id_meal: 22, id_ingredient: 234, str_measure: '3 tbs' },
        { id_meal: 22, id_ingredient: 365, str_measure: '400g' },
        { id_meal: 22, id_ingredient: 316, str_measure: '5' },
        { id_meal: 22, id_ingredient: 253, str_measure: '350g' },
        { id_meal: 23, id_ingredient: 304, str_measure: '500g' },
        { id_meal: 23, id_ingredient: 115, str_measure: '400ml' },
        { id_meal: 23, id_ingredient: 210, str_measure: '3 x 7.5cm' },
        { id_meal: 23, id_ingredient: 155, str_measure: '1 tbsp' },
        { id_meal: 23, id_ingredient: 214, str_measure: 'sprigs of fresh' },
        { id_meal: 24, id_ingredient: 439, str_measure: '250g' },
        { id_meal: 24, id_ingredient: 443, str_measure: '2 tbs' },
        { id_meal: 24, id_ingredient: 364, str_measure: '1 sliced' },
        { id_meal: 24, id_ingredient: 440, str_measure: '0.25' },
        { id_meal: 24, id_ingredient: 441, str_measure: '10' },
        { id_meal: 24, id_ingredient: 301, str_measure: '4' },
        { id_meal: 24, id_ingredient: 442, str_measure: '4 tbsp' },
        { id_meal: 24, id_ingredient: 296, str_measure: '2 tbs' },
        { id_meal: 24, id_ingredient: 52, str_measure: '1 tblsp' },
        { id_meal: 24, id_ingredient: 342, str_measure: '1 tblsp' },
        { id_meal: 25, id_ingredient: 387, str_measure: '1/4 lb' },
        { id_meal: 25, id_ingredient: 364, str_measure: '1' },
        { id_meal: 25, id_ingredient: 123, str_measure: '3' },
        { id_meal: 25, id_ingredient: 74, str_measure: '1 tbs' },
        { id_meal: 25, id_ingredient: 444, str_measure: '1/2 ' },
        { id_meal: 25, id_ingredient: 281, str_measure: 'To taste' },
        { id_meal: 25, id_ingredient: 244, str_measure: 'To taste' },
        { id_meal: 25, id_ingredient: 576, str_measure: 'Top' },
      ],
      {},
    );
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete('ingredients_measures_meals', {});
  },
};
